import type { Metadata } from 'next';

// These styles apply to every route in the application
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="overflow-hidden bg-brutal-background text-brutal-on-background">
        <div id="body" className="relative h-screen w-full overflow-y-auto overflow-x-hidden">
          {children}
        </div>
      </body>
    </html>
  );
}
